# Generated by Django 5.2.6 on 2025-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_student_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="auto_generated_password",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Avtomatik parol"
            ),
        ),
    ]
