# Generated by Django 5.2.6 on 2025-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_student_auto_generated_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisor",
            name="auto_generated_password",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Avtomatik parol"
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="is_password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
