# Generated by Django 5.2.6 on 2025-09-27 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0005_rename_auto_generated_password_supervisor_supervisor_password_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="supervisor",
            old_name="supervisor_password",
            new_name="auto_generated_password",
        ),
    ]
