# Generated by Django 5.2.6 on 2025-09-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_supervisor_password_supervisor_auto_generated_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisor",
            name="supervisor_id",
            field=models.CharField(
                default=111, max_length=20, unique=True, verbose_name="Rahbar ID"
            ),
            preserve_default=False,
        ),
    ]
