# Generated by Django 5.2.6 on 2025-09-28 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_supervisor_supervisor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
