# Generated by Django 5.2.6 on 2025-10-13 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_company_options_alter_dailyreport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisor",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.company",
                verbose_name="Korxona",
            ),
        ),
    ]
