# Generated by Django 5.2.6 on 2025-10-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_supervisor_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon raqam"
            ),
        ),
    ]
