# Generated by Django 5.2.6 on 2025-10-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_internship_created_by_internship_duration_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Kutilmoqda"),
                    ("assigned", "Belgilangan"),
                    ("start_pending", "Boshlash kutilmoqda"),
                    ("started", "Boshlangan"),
                    ("completed", "Tugadi"),
                    ("grading", "Baholash"),
                    ("graded", "Baholandi"),
                    ("confirmed", "Tasdiqlandi"),
                    ("cancelled", "Bekor qilingan"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DailyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("day_start", "Kunni boshlash"),
                            ("start_confirmed", "Boshlash tasdiqlandi"),
                            ("report_submitted", "Hisobot topshirish"),
                            ("report_confirmed", "Hisobot tasdiqlandi"),
                            ("day_completed", "Yakunlash"),
                        ],
                        default="day_start",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_statuses",
                        to="api.internship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kunlik status",
                "verbose_name_plural": "Kunlik statuslar",
                "unique_together": {("internship", "date")},
            },
        ),
    ]
