# Generated by Django 5.2.6 on 2025-10-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_internship_status_dailystatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystatus",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Rad etish sababi"
            ),
        ),
        migrations.AlterField(
            model_name="dailystatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("day_start", "Kunni boshlash"),
                    ("start_confirmed", "Boshlash tasdiqlandi"),
                    ("start_rejected", "Boshlash rad etildi"),
                    ("report_submitted", "Hisobot topshirish"),
                    ("report_confirmed", "Hisobot tasdiqlandi"),
                    ("report_rejected", "Hisobot rad etildi"),
                    ("resubmitted", "Qayta topshirish"),
                    ("day_completed", "Yakunlash"),
                ],
                default="day_start",
                max_length=20,
            ),
        ),
    ]
