# Generated by Django 5.2.6 on 2025-10-24 05:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_dailystatus_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="grade_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Baholash izohi"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="graded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Baholangan vaqt"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_internships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="is_graded",
            field=models.BooleanField(default=False, help_text="Baholanganmi?"),
        ),
        migrations.AlterField(
            model_name="internship",
            name="grade",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Yakuniy baho",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Umumiy baho",
            ),
        ),
    ]
