# Generated by Django 5.2.6 on 2025-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_add_grade_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Kutilmoqda"),
                    ("assigned", "Belgilangan"),
                    ("start_pending", "Boshlash kutilmoqda"),
                    ("started", "Boshlangan"),
                    ("completed", "Tugadi"),
                    ("grading", "Baholash"),
                    ("graded", "Baholandi"),
                    ("confirmed", "Tasdiqlandi"),
                    ("cancelled", "Bekor qilingan"),
                ],
                default="start_pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="internship_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Kutilmoqda"),
                    ("assigned", "Belgilangan"),
                    ("start_pending", "Boshlash kutilmoqda"),
                    ("started", "Boshlangan"),
                    ("completed", "Tugadi"),
                    ("grading", "Baholash"),
                    ("graded", "Baholandi"),
                    ("confirmed", "Tasdiqlandi"),
                    ("cancelled", "Bekor qilingan"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
