# Generated by Django 5.2.6 on 2025-10-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_internship_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("contract", "Shartnoma"),
                    ("program", "Dastur"),
                    ("report", "Hisobot"),
                    ("certificate", "Sertifikat"),
                    ("other", "Boshqa"),
                ],
                max_length=20,
            ),
        ),
    ]
