# Generated by Django 5.2.6 on 2025-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="rejection_reason",
            field=models.TextField(blank=True, help_text="Rad etish sababi", null=True),
        ),
    ]
