# Generated by Django 5.2.6 on 2025-10-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_document_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="photos",
            field=models.JSONField(
                blank=True, default=list, help_text="Hisobot rasmlari"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="rejection_reason",
            field=models.TextField(blank=True, help_text="Rad etish sababi", null=True),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="supervisor_comment",
            field=models.TextField(blank=True, help_text="Rahbar izohi", null=True),
        ),
    ]
