import { useState } from 'react';
import { X, Save, User, FileText } from 'lucide-react';
import { Student } from '../../types';
import { useFaculties, useDepartments } from '../../hooks/useData';

interface StudentFormProps {
  student?: Student;
  onSave: (student: Omit<Student, 'id'>) => void;
  onClose: () => void;
}

export function StudentForm({ student, onSave, onClose }: StudentFormProps) {
  const { faculties, loading: facultiesLoading } = useFaculties();
  const { departments, loading: departmentsLoading } = useDepartments();
  
  const [formData, setFormData] = useState<Omit<Student, 'id'>>({
    name: student?.name || '',
    studentId: student?.studentId || '',
    hemisId: student?.hemisId || '',
    faculty: student?.faculty || '',
    department: student?.department || '',
    course: student?.course || 1,
    group: student?.group || '',
    phone: student?.phone || '',
    birthDate: student?.birthDate || '',
    passport: student?.passport || '',
    address: student?.address || '',
    parentPhone: student?.parentPhone || '',
    internshipType: student?.internshipType || 'belgilanmagan',
    internshipStatus: student?.internshipStatus || 'waiting',
    supervisorId: student?.supervisorId,
    companyId: student?.companyId,
    grade: student?.grade,
    startDate: student?.startDate || '',
    endDate: student?.endDate || '',
    autoGeneratedPassword: student?.autoGeneratedPassword || '',
    isPasswordChanged: student?.isPasswordChanged || false,
    // HEMIS qo'shimcha ma'lumotlari
    region: student?.region || '',
    district: student?.district || '',
    gender: student?.gender || '',
    jshshir: student?.jshshir || '',
    academicYear: student?.academicYear || '',
    semester: student?.semester || '',
    isGraduate: student?.isGraduate || '',
    educationLanguage: student?.educationLanguage || '',
    specialization: student?.specialization || '',
    educationType: student?.educationType || '',
    educationForm: student?.educationForm || ''
  });

  // Filter departments based on selected faculty
  const filteredDepartments = departments.filter(dept => 
    dept.faculty_name === formData.faculty || dept.faculty === formData.faculty
  );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Generate password if new student
    if (!student) {
      const firstName = formData.name.split(' ')[0].toLowerCase();
      const year = new Date().getFullYear();
      formData.autoGeneratedPassword = `${firstName}${year}`;
      formData.isPasswordChanged = false;
    }
    
    onSave(formData);
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: name === 'course' ? parseInt(value) : value,
      // Reset department when faculty changes
      ...(name === 'faculty' && { department: '' })
    }));
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <h2 className="text-xl font-bold text-gray-900">
            {student ? 'Talabani tahrirlash' : 'Yangi talaba qo\'shish'}
          </h2>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg"
          >
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Personal Information */}
            <div className="space-y-4">
              <h3 className="text-lg font-semibold text-gray-900 flex items-center">
                <User className="mr-2" size={20} />
                Shaxsiy ma'lumotlar
              </h3>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  To'liq ismi *
                </label>
                <input
                  type="text"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  required
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Talaba ID *
                  </label>
                  <input
                    type="text"
                    name="studentId"
                    value={formData.studentId}
                    onChange={handleChange}
                    required
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    HEMIS ID
                  </label>
                  <input
                    type="text"
                    name="hemisId"
                    value={formData.hemisId}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
              </div>


              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Telefon
                  </label>
                  <input
                    type="tel"
                    name="phone"
                    value={formData.phone}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Ota-ona telefoni
                  </label>
                  <input
                    type="tel"
                    name="parentPhone"
                    value={formData.parentPhone}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Tug'ilgan sana
                  </label>
                  <input
                    type="date"
                    name="birthDate"
                    value={formData.birthDate}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Passport seriyasi
                  </label>
                  <input
                    type="text"
                    name="passport"
                    value={formData.passport}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Manzil
                </label>
                <textarea
                  name="address"
                  value={formData.address}
                  onChange={handleChange}
                  rows={2}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>

            {/* Academic Information */}
            <div className="space-y-4">
              <h3 className="text-lg font-semibold text-gray-900 flex items-center">
                <FileText className="mr-2" size={20} />
                Ta'lim ma'lumotlari
              </h3>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Fakultet *
                </label>
                <select
                  name="faculty"
                  value={formData.faculty}
                  onChange={handleChange}
                  required
                  disabled={facultiesLoading}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100"
                >
                  <option value="">Fakultetni tanlang</option>
                  {faculties.map(faculty => (
                    <option key={faculty.id} value={faculty.name}>
                      {faculty.name}
                    </option>
                  ))}
                </select>
                {facultiesLoading && (
                  <p className="text-sm text-gray-500 mt-1">Fakultetlar yuklanmoqda...</p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Kafedra *
                </label>
                <select
                  name="department"
                  value={formData.department}
                  onChange={handleChange}
                  required
                  disabled={departmentsLoading || !formData.faculty}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100"
                >
                  <option value="">Kafedrani tanlang</option>
                  {filteredDepartments.map(department => (
                    <option key={department.id} value={department.name}>
                      {department.name}
                    </option>
                  ))}
                </select>
                {departmentsLoading && (
                  <p className="text-sm text-gray-500 mt-1">Kafedralar yuklanmoqda...</p>
                )}
                {!formData.faculty && !departmentsLoading && (
                  <p className="text-sm text-gray-500 mt-1">Avval fakultetni tanlang</p>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Kurs *
                  </label>
                  <select
                    name="course"
                    value={formData.course}
                    onChange={handleChange}
                    required
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    <option value={1}>1-kurs</option>
                    <option value={2}>2-kurs</option>
                    <option value={3}>3-kurs</option>
                    <option value={4}>4-kurs</option>
                    <option value={5}>5-kurs</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Guruh *
                  </label>
                  <input
                    type="text"
                    name="group"
                    value={formData.group}
                    onChange={handleChange}
                    required
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Amaliyot turi *
                </label>
                {/* <select
                  name="internshipType"
                  value={formData.internshipType}
                  onChange={handleChange}
                  required
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="belgilanmagan">Belgilanmagan</option>
                  <option value="malaka">Malaka amaliyoti</option>
                  <option value="pedagogik">Pedagogik amaliyot</option>
                  <option value="ilmiy">Ilmiy amaliyot</option>
                  <option value="ishlab_chiqarish">Ishlab chiqarish amaliyoti</option>
                </select> */}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Holat
                </label>
                <select
                  name="internshipStatus"
                  value={formData.internshipStatus}
                  onChange={handleChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="waiting">Kutish</option>
                  <option value="assigned">Tayinlangan</option>
                  <option value="active">Faol</option>
                  <option value="completed">Yakunlangan</option>
                </select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Boshlanish sanasi
                  </label>
                  <input
                    type="date"
                    name="startDate"
                    value={formData.startDate}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Tugash sanasi
                  </label>
                  <input
                    type="date"
                    name="endDate"
                    value={formData.endDate}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
              </div>

              {formData.grade !== undefined && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Baho
                  </label>
                  <input
                    type="number"
                    name="grade"
                    value={formData.grade || ''}
                    onChange={handleChange}
                    min="0"
                    max="100"
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
              )}
            </div>
          </div>

          {/* HEMIS qo'shimcha ma'lumotlari */}
          <div className="mt-8 pt-6 border-t border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900 flex items-center mb-6">
              <FileText className="mr-2" size={20} />
              HEMIS qo'shimcha ma'lumotlari
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {/* Shaxsiy ma'lumotlar */}
              <div className="space-y-4">
                <h4 className="text-md font-medium text-gray-800">Shaxsiy ma'lumotlar</h4>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    JSHSHIR kod
                  </label>
                  <input
                    type="text"
                    name="jshshir"
                    value={formData.jshshir || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Jins
                  </label>
                  <select
                    name="gender"
                    value={formData.gender || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    <option value="">Tanlang</option>
                    <option value="Erkak">Erkak</option>
                    <option value="Ayol">Ayol</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Viloyat
                  </label>
                  <input
                    type="text"
                    name="region"
                    value={formData.region || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Tuman
                  </label>
                  <input
                    type="text"
                    name="district"
                    value={formData.district || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
              </div>

              {/* Ta'lim ma'lumotlari */}
              <div className="space-y-4">
                <h4 className="text-md font-medium text-gray-800">Ta'lim ma'lumotlari</h4>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Ta'lim tili
                  </label>
                  <select
                    name="educationLanguage"
                    value={formData.educationLanguage || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    <option value="">Tanlang</option>
                    <option value="O'zbek">O'zbek</option>
                    <option value="Rus">Rus</option>
                    <option value="Ingliz">Ingliz</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    O'quv yili
                  </label>
                  <input
                    type="text"
                    name="academicYear"
                    value={formData.academicYear || ''}
                    onChange={handleChange}
                    placeholder="2024-2025"
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Semestr
                  </label>
                  <input
                    type="text"
                    name="semester"
                    value={formData.semester || ''}
                    onChange={handleChange}
                    placeholder="5-semestr"
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Bitiruvchi
                  </label>
                  <select
                    name="isGraduate"
                    value={formData.isGraduate || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    <option value="">Tanlang</option>
                    <option value="Ha">Ha</option>
                    <option value="Yo'q">Yo'q</option>
                  </select>
                </div>
              </div>

              {/* Mutaxassislik ma'lumotlari */}
              <div className="space-y-4">
                <h4 className="text-md font-medium text-gray-800">Mutaxassislik</h4>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Mutaxassislik
                  </label>
                  <input
                    type="text"
                    name="specialization"
                    value={formData.specialization || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Ta'lim turi
                  </label>
                  <select
                    name="educationType"
                    value={formData.educationType || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    <option value="">Tanlang</option>
                    <option value="Bakalavr">Bakalavr</option>
                    <option value="Magistr">Magistr</option>
                    <option value="Doktorantura">Doktorantura</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Ta'lim shakli
                  </label>
                  <select
                    name="educationForm"
                    value={formData.educationForm || ''}
                    onChange={handleChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  >
                    <option value="">Tanlang</option>
                    <option value="Kunduzgi">Kunduzgi</option>
                    <option value="Kechki">Kechki</option>
                    <option value="Sirtqi">Sirtqi</option>
                  </select>
                </div>
              </div>
            </div>
          </div>

          <div className="flex justify-end space-x-4 mt-8 pt-6 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Bekor qilish
            </button>
            <button
              type="submit"
              className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center"
            >
              <Save size={20} className="mr-2" />
              Saqlash
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}