# Generated by Django 5.2.6 on 2025-09-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="auto_generated_password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="hemis_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parent_phone",
        ),
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="O'quv yili"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tuman"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="education_form",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ta'lim shakli"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="education_language",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ta'lim tili"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="education_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ta'lim turi"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Jins"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="is_graduate",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Bitiruvchi"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="jshshir",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="JSHSHIR kod"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Viloyat"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Semestr"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="specialization",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Mutaxassislik"
            ),
        ),
    ]
