# Generated by Django 5.2.6 on 2025-09-27 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_supervisor_auto_generated_password_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supervisor",
            old_name="auto_generated_password",
            new_name="supervisor_password",
        ),
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
    ]
