# Generated by Django 5.2.6 on 2025-10-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Korxona",
                "verbose_name_plural": "Korxonalar",
            },
        ),
        migrations.AlterModelOptions(
            name="dailyreport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Kundalik hisobot",
                "verbose_name_plural": "Kundalik hisobotlar",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["faculty", "name"],
                "verbose_name": "Kafedra",
                "verbose_name_plural": "Kafedralar",
            },
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={
                "ordering": ["name"],
                "verbose_name": "Fakultet",
                "verbose_name_plural": "Fakultetlar",
            },
        ),
        migrations.AlterModelOptions(
            name="internship",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Amaliyot",
                "verbose_name_plural": "Amaliyotlar",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Talaba",
                "verbose_name_plural": "Talabalar",
            },
        ),
        migrations.AlterModelOptions(
            name="supervisor",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Rahbar",
                "verbose_name_plural": "Rahbarlar",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="work_days",
            field=models.JSONField(default=list, help_text="Ish kunlari ro'yxati"),
        ),
        migrations.AddField(
            model_name="company",
            name="work_hours_end",
            field=models.TimeField(default="18:00", help_text="Ish tugash vaqti"),
        ),
        migrations.AddField(
            model_name="company",
            name="work_hours_start",
            field=models.TimeField(default="09:00", help_text="Ish boshlanish vaqti"),
        ),
        migrations.AlterField(
            model_name="student",
            name="internship_type",
            field=models.CharField(
                choices=[
                    ("belgilanmagan", "Belgilanmagan"),
                    ("malaka", "Malaka amaliyoti"),
                    ("pedagogik", "Pedagogik amaliyot"),
                    ("ilmiy", "Ilmiy amaliyot"),
                    ("ishlab_chiqarish", "Ishlab chiqarish amaliyoti"),
                ],
                default="belgilanmagan",
                max_length=20,
            ),
        ),
    ]
