# Generated by Django 5.2.6 on 2025-10-15 06:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_internships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="duration_days",
            field=models.IntegerField(
                blank=True,
                help_text="Amaliyot kunlari soni",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Amaliyot faolmi"),
        ),
    ]
