# Generated by Django 5.2.6 on 2025-10-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_dailyreport_photos_dailyreport_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, help_text="Hujjat tavsifi", null=True),
        ),
    ]
