import { useState, useEffect } from 'react';
import { Student, Supervisor, Statistics, DailyReport, HemisStudent, ImportResult, Company, Faculty, Department, Document, InternshipPlace, Grade, AdminSettings } from '../types';
import apiService from '../services/api';

// Students hook
export function useStudents() {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchStudents = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await apiService.getStudents() as any;
      const studentsData = response.results || response;
      
      // Backend ma'lumotlarini frontend formatiga o'tkazish
      const mappedStudents = studentsData.map((student: any) => {
        console.log('Student data:', student); // Debug
        return {
        id: student.id,
        name: (student.user?.first_name && student.user?.last_name) 
          ? `${student.user.first_name} ${student.user.last_name}` 
          : student.user?.first_name || student.user?.last_name || student.user?.username || 'Noma\'lum',
        studentId: student.student_id,
        student_id: student.student_id, // Qo'shimcha field
        hemisId: student.student_id,
        faculty: student.faculty_name || student.faculty,
        department: student.department_name || student.department,
        course: student.course,
        group: student.group,
        phone: student.user?.phone || '',
        birthDate: student.birth_date,
        passport: student.passport,
        address: student.address,
        parentPhone: student.parent_phone,
        internshipType: student.internship_type,
        internshipStatus: student.internship_status,
        supervisorId: student.supervisor,
        companyId: student.company,
        supervisorName: student.supervisor_name,
        supervisorPosition: student.supervisor_position,
        companyName: student.company_name,
        companyAddress: student.company_address,
        grade: student.grade,
        startDate: student.start_date,
        endDate: student.end_date,
        autoGeneratedPassword: student.auto_generated_password,
        isPasswordChanged: student.is_password_changed,
        login_info: student.user?.login_info, // Login ma'lumotlari
        // HEMIS qo'shimcha ma'lumotlari
        region: student.region,
        district: student.district,
        gender: student.gender, 
        jshshir: student.jshshir,
        educationLanguage: student.education_language,
        academicYear: student.academic_year,
        semester: student.semester,
        isGraduate: student.is_graduate,
        specialization: student.specialization,
        educationType: student.education_type,
        educationForm: student.education_form,
      };
      });
      
      setStudents(mappedStudents);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Xatolik yuz berdi');
      console.error('Students fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStudents();
  }, []);

  const addStudent = async (student: Omit<Student, 'id'>) => {
    try {
      const newStudent = await apiService.createStudent(student) as any;
    setStudents(prev => [...prev, newStudent]);
      return newStudent;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Talaba yaratishda xatolik');
      throw err;
    }
  };

  const updateStudent = async (id: string, updates: Partial<Student>) => {
    try {
      const updatedStudent = await apiService.updateStudent(id, updates) as any;
      
      // Backend ma'lumotlarini frontend formatiga o'tkazish
      const mappedStudent = {
        id: updatedStudent.id,
        name: (updatedStudent.user?.first_name && updatedStudent.user?.last_name) 
          ? `${updatedStudent.user.first_name} ${updatedStudent.user.last_name}` 
          : updatedStudent.user?.first_name || updatedStudent.user?.last_name || updatedStudent.user?.username || 'Noma\'lum',
        studentId: updatedStudent.student_id,
        hemisId: updatedStudent.student_id,
        faculty: updatedStudent.faculty_name || updatedStudent.faculty,
        department: updatedStudent.department_name || updatedStudent.department,
        course: updatedStudent.course,
        group: updatedStudent.group,
        phone: updatedStudent.user?.phone || '',
        birthDate: updatedStudent.birth_date,
        passport: updatedStudent.passport,
        address: updatedStudent.address,
        parentPhone: updatedStudent.parent_phone,
        internshipType: updatedStudent.internship_type,
        internshipStatus: updatedStudent.internship_status,
        supervisorId: updatedStudent.supervisor,
        companyId: updatedStudent.company,
        supervisorName: updatedStudent.supervisor_name,
        supervisorPosition: updatedStudent.supervisor_position,
        companyName: updatedStudent.company_name,
        companyAddress: updatedStudent.company_address,
        grade: updatedStudent.grade,
        startDate: updatedStudent.start_date,
        endDate: updatedStudent.end_date,
        autoGeneratedPassword: updatedStudent.auto_generated_password,
        isPasswordChanged: updatedStudent.is_password_changed,
        // HEMIS qo'shimcha ma'lumotlari
        region: updatedStudent.region,
        district: updatedStudent.district,
        gender: updatedStudent.gender,
        jshshir: updatedStudent.jshshir,
        educationLanguage: updatedStudent.education_language,
        academicYear: updatedStudent.academic_year,
        semester: updatedStudent.semester,
        isGraduate: updatedStudent.is_graduate,
        specialization: updatedStudent.specialization,
        educationType: updatedStudent.education_type,
        educationForm: updatedStudent.education_form,
      };
      
      setStudents(prev => 
        prev.map(student => 
            student.id === id ? mappedStudent : student
        )
      );
      return mappedStudent;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Talaba yangilashda xatolik');
      throw err;
    }
  };

  const deleteStudent = async (id: string) => {
    try {
      await apiService.deleteStudent(id);
    setStudents(prev => prev.filter(student => student.id !== id));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Talaba o\'chirishda xatolik');
      throw err;
    }
  };

  const assignSupervisor = async (studentId: string, supervisorId: string) => {
    try {
      const updatedStudent = await apiService.updateStudent(studentId, {
        supervisorId,
        internshipStatus: 'assigned'
      }) as any;
      
      // Backend ma'lumotlarini frontend formatiga o'tkazish
      const mappedStudent = {
        id: updatedStudent.id,
        name: (updatedStudent.user?.first_name && updatedStudent.user?.last_name) 
          ? `${updatedStudent.user.first_name} ${updatedStudent.user.last_name}` 
          : updatedStudent.user?.first_name || updatedStudent.user?.last_name || updatedStudent.user?.username || 'Noma\'lum',
        studentId: updatedStudent.student_id,
        hemisId: updatedStudent.student_id,
        faculty: updatedStudent.faculty_name || updatedStudent.faculty,
        department: updatedStudent.department_name || updatedStudent.department,
        course: updatedStudent.course,
        group: updatedStudent.group,
        phone: updatedStudent.user?.phone || '',
        birthDate: updatedStudent.birth_date,
        passport: updatedStudent.passport,
        address: updatedStudent.address,
        parentPhone: updatedStudent.parent_phone,
        internshipType: updatedStudent.internship_type,
        internshipStatus: updatedStudent.internship_status,
        supervisorId: updatedStudent.supervisor,
        companyId: updatedStudent.company,
        supervisorName: updatedStudent.supervisor_name,
        supervisorPosition: updatedStudent.supervisor_position,
        companyName: updatedStudent.company_name,
        companyAddress: updatedStudent.company_address,
        grade: updatedStudent.grade,
        startDate: updatedStudent.start_date,
        endDate: updatedStudent.end_date,
        autoGeneratedPassword: updatedStudent.auto_generated_password,
        isPasswordChanged: updatedStudent.is_password_changed,
        // HEMIS qo'shimcha ma'lumotlari
        region: updatedStudent.region,
        district: updatedStudent.district,
        gender: updatedStudent.gender,
        jshshir: updatedStudent.jshshir,
        educationLanguage: updatedStudent.education_language,
        academicYear: updatedStudent.academic_year,
        semester: updatedStudent.semester,
        isGraduate: updatedStudent.is_graduate,
        specialization: updatedStudent.specialization,
        educationType: updatedStudent.education_type,
        educationForm: updatedStudent.education_form,
      };
      
      setStudents(prev => 
        prev.map(student => 
            student.id === studentId ? mappedStudent : student
        )
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Rahbar tayinlashda xatolik');
      throw err;
    }
  };

  const importFromHemis = async (hemisData: HemisStudent[]): Promise<ImportResult> => {
    try {
      const result = await apiService.importHemisData(hemisData as any) as any;
      if (result.success > 0) {
        await fetchStudents(); // Refresh students list
      }
      return result;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Import xatoligi');
      throw err;
    }
  };

  return { 
    students, 
    loading, 
    error,
    addStudent, 
    updateStudent, 
    deleteStudent, 
    assignSupervisor, 
    importFromHemis,
    refresh: fetchStudents
  };
}

// Supervisors hook
export function useSupervisors() {
  const [supervisors, setSupervisors] = useState<Supervisor[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchSupervisors = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await apiService.getSupervisors() as any;
      const supervisorsData = response.results || response;

      const mappedSupervisors = supervisorsData.map((supervisor: any) => ({
          id: supervisor.id, // Supervisor ID (9, 10, 11, ...)
          name: supervisor.user?.first_name && supervisor.user?.last_name
            ? `${supervisor.user.first_name} ${supervisor.user.last_name}`
            : supervisor.user?.username || 'Noma\'lum',
          position: supervisor.position,
          department: supervisor.department_name || supervisor.department,
          faculty: supervisor.faculty_name || supervisor.faculty,
          phone: supervisor.user?.phone || '',
          specialization: supervisor.specialization,
          capacity: supervisor.capacity,
          assignedStudents: supervisor.assigned_students || 0,
          rating: supervisor.rating || 0,
          status: supervisor.status,
          experience: supervisor.experience || 0,
          autoGeneratedPassword: supervisor.auto_generated_password,
          isPasswordChanged: supervisor.is_password_changed,
          supervisorId: supervisor.supervisor_id,
          company: supervisor.company,
          company_name: supervisor.company_name,
          // Debug uchun qo'shimcha ma'lumotlar
          user_id: supervisor.user?.id, // User ID (504, 505, ...)
          supervisor_user_id: supervisor.user?.id
        }));
      
      setSupervisors(mappedSupervisors);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Xatolik yuz berdi');
      console.error('Supervisors fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSupervisors();
  }, []);

  const addSupervisor = async (supervisor: Omit<Supervisor, 'id'>) => {
    try {
      const newSupervisor = await apiService.createSupervisor(supervisor) as any;
      
      // Backend dan kelgan ma'lumotni frontend formatiga o'tkazish
      const mappedSupervisor = {
        id: newSupervisor.id,
        name: newSupervisor.user?.first_name && newSupervisor.user?.last_name
          ? `${newSupervisor.user.first_name} ${newSupervisor.user.last_name}`
          : newSupervisor.user?.username || 'Noma\'lum',
        position: newSupervisor.position,
        department: newSupervisor.department_name || newSupervisor.department,
        faculty: newSupervisor.faculty_name || newSupervisor.faculty,
        phone: newSupervisor.user?.phone || '',
        specialization: newSupervisor.specialization,
        capacity: newSupervisor.capacity,
        assignedStudents: newSupervisor.assigned_students || 0,
        rating: newSupervisor.rating || 0,
        status: newSupervisor.status,
        experience: newSupervisor.experience || 0,
        autoGeneratedPassword: newSupervisor.auto_generated_password,
        isPasswordChanged: newSupervisor.is_password_changed,
        supervisorId: newSupervisor.supervisor_id,
        company: newSupervisor.company,
        company_name: newSupervisor.company_name
      };
      
      setSupervisors(prev => [...prev, mappedSupervisor]);
      return mappedSupervisor;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Rahbar yaratishda xatolik');
      throw err;
    }
  };

  const updateSupervisor = async (id: string, updates: Partial<Supervisor>) => {
    try {
      const updatedSupervisor = await apiService.updateSupervisor(id, updates) as any;
      
      // Backend dan kelgan ma'lumotni frontend formatiga o'tkazish
      const mappedSupervisor = {
        id: updatedSupervisor.id,
        name: updatedSupervisor.user?.first_name && updatedSupervisor.user?.last_name
          ? `${updatedSupervisor.user.first_name} ${updatedSupervisor.user.last_name}`
          : updatedSupervisor.user?.username || 'Noma\'lum',
        position: updatedSupervisor.position,
        department: updatedSupervisor.department_name || updatedSupervisor.department,
        faculty: updatedSupervisor.faculty_name || updatedSupervisor.faculty,
        phone: updatedSupervisor.user?.phone || '',
        specialization: updatedSupervisor.specialization,
        capacity: updatedSupervisor.capacity,
        assignedStudents: updatedSupervisor.assigned_students || 0,
        rating: updatedSupervisor.rating || 0,
        status: updatedSupervisor.status,
        experience: updatedSupervisor.experience || 0,
        autoGeneratedPassword: updatedSupervisor.auto_generated_password,
        isPasswordChanged: updatedSupervisor.is_password_changed,
        supervisorId: updatedSupervisor.supervisor_id,
        company: updatedSupervisor.company,
        company_name: updatedSupervisor.company_name
      };
      
      setSupervisors(prev => 
        prev.map(supervisor => 
          supervisor.id === id ? mappedSupervisor : supervisor
        )
      );
      return mappedSupervisor;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Rahbar yangilashda xatolik');
      throw err;
    }
  };

  const deleteSupervisor = async (id: string) => {
    try {
      await apiService.deleteSupervisor(id);
    setSupervisors(prev => prev.filter(supervisor => supervisor.id !== id));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Rahbar o\'chirishda xatolik');
      throw err;
    }
  };

  const updateSupervisorCapacity = async (supervisorId: string, increment: number) => {
    try {
      const supervisor = supervisors.find(s => s.id === supervisorId);
      if (!supervisor) {
        throw new Error(`Supervisor topilmadi: ${supervisorId}`);
      }

      const newAssignedCount = supervisor.assignedStudents + increment;
      if (newAssignedCount < 0) {
        throw new Error('Assigned students soni manfiy bo\'lishi mumkin emas');
      }
      if (newAssignedCount > supervisor.capacity) {
        throw new Error(`Supervisor sig'imi yetarli emas. Mavjud: ${supervisor.capacity}, Talab: ${newAssignedCount}`);
      }

      const updatedSupervisor = await apiService.updateSupervisor(supervisorId, {
        assigned_students: newAssignedCount
      }) as any;

      // Backend dan kelgan ma'lumotni frontend formatiga o'tkazish
      const mappedSupervisor = {
        id: updatedSupervisor.id,
        name: updatedSupervisor.user?.first_name && updatedSupervisor.user?.last_name
          ? `${updatedSupervisor.user.first_name} ${updatedSupervisor.user.last_name}`
          : updatedSupervisor.user?.username || 'Noma\'lum',
        position: updatedSupervisor.position,
        department: updatedSupervisor.department_name || updatedSupervisor.department,
        faculty: updatedSupervisor.faculty_name || updatedSupervisor.faculty,
        phone: updatedSupervisor.user?.phone || '',
        specialization: updatedSupervisor.specialization,
        capacity: updatedSupervisor.capacity,
        assignedStudents: updatedSupervisor.assigned_students || 0,
        rating: updatedSupervisor.rating || 0,
        status: updatedSupervisor.status,
        experience: updatedSupervisor.experience || 0,
        autoGeneratedPassword: updatedSupervisor.auto_generated_password,
        isPasswordChanged: updatedSupervisor.is_password_changed,
        supervisorId: updatedSupervisor.supervisor_id,
        company: updatedSupervisor.company,
        company_name: updatedSupervisor.company_name,
        user_id: updatedSupervisor.user?.id,
      };

      setSupervisors(prev => 
        prev.map(s => s.id === supervisorId ? mappedSupervisor : s)
      );
      
      return mappedSupervisor;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Supervisor sig\'imi yangilashda xatolik');
      throw err;
    }
  };

  return { 
    supervisors, 
    loading, 
    error, 
    addSupervisor, 
    updateSupervisor, 
    deleteSupervisor,
    updateSupervisorCapacity,
    refresh: fetchSupervisors
  };
}

// Companies hook
export function useCompanies() {
  const [companies, setCompanies] = useState<Company[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchCompanies = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await apiService.getCompanies() as any;
      const companiesData = response.results || response;

      const mappedCompanies = companiesData.map((company: any) => ({
        id: company.id,
        name: company.name,
        direction: company.direction,
        address: company.address,
        phone: company.phone,
        capacity: company.capacity,
        assignedStudents: company.assigned_students || 0,
        rating: company.rating || 0,
        status: company.status,
        work_days: company.work_days || [],
        work_days_display: company.work_days_display || [],
        work_hours_start: company.work_hours_start || '09:00:00',
        work_hours_end: company.work_hours_end || '18:00:00'
      }));
      
      setCompanies(mappedCompanies);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Xatolik yuz berdi');
      console.error('Companies fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCompanies();
  }, []);

  const addCompany = async (company: Omit<Company, 'id'>) => {
    try {
      const newCompany = await apiService.createCompany(company) as any;
    setCompanies(prev => [...prev, newCompany]);
      return newCompany;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Korxona yaratishda xatolik');
      throw err;
    }
  };

  const updateCompany = async (id: string, updates: Partial<Company>) => {
    try {
      const updatedCompany = await apiService.updateCompany(id, updates) as any;
    setCompanies(prev => 
      prev.map(company => 
          company.id === id ? updatedCompany : company
      )
    );
      return updatedCompany;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Korxona yangilashda xatolik');
      throw err;
    }
  };

  const deleteCompany = async (id: string) => {
    try {
      await apiService.deleteCompany(id);
    setCompanies(prev => prev.filter(company => company.id !== id));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Korxona o\'chirishda xatolik');
      throw err;
    }
  };

  const updateCompanyCapacity = async (companyId: string, increment: number) => {
    try {
      const company = companies.find(c => c.id === companyId);
      if (!company) {
        throw new Error('Company topilmadi');
      }

      const newAssignedCount = company.assignedStudents + increment;
      if (newAssignedCount < 0) {
        throw new Error('Assigned students soni manfiy bo\'lishi mumkin emas');
      }
      if (newAssignedCount > company.capacity) {
        throw new Error(`Company sig'imi yetarli emas. Mavjud: ${company.capacity}, Talab: ${newAssignedCount}`);
      }

      const updatedCompany = await apiService.updateCompany(companyId, {
        assigned_students: newAssignedCount
      }) as any;

      // Backend dan kelgan ma'lumotni frontend formatiga o'tkazish
      const mappedCompany = {
        id: updatedCompany.id,
        name: updatedCompany.name,
        direction: updatedCompany.direction,
        address: updatedCompany.address,
        phone: updatedCompany.phone,
        capacity: updatedCompany.capacity,
        assignedStudents: updatedCompany.assigned_students || 0,
        rating: updatedCompany.rating || 0,
        status: updatedCompany.status,
        work_days: updatedCompany.work_days || [],
        work_days_display: updatedCompany.work_days_display || [],
        work_hours_start: updatedCompany.work_hours_start || '09:00:00',
        work_hours_end: updatedCompany.work_hours_end || '18:00:00'
      };

      setCompanies(prev => 
        prev.map(c => c.id === companyId ? mappedCompany : c)
      );
      
      return mappedCompany;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Company sig\'imi yangilashda xatolik');
      throw err;
    }
  };

  return { 
    companies, 
    loading, 
    error,
    addCompany, 
    updateCompany, 
    deleteCompany,
    updateCompanyCapacity,
    refresh: fetchCompanies
  };
}

// Daily Reports hook
export function useDailyReports() {
  const [reports, setReports] = useState<DailyReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchReports = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await apiService.getDailyReports() as any;
      setReports(response.results || response);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Xatolik yuz berdi');
      console.error('Daily reports fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const addReport = async (report: Omit<DailyReport, 'id'>) => {
    try {
      // FormData yaratish
      const formData = new FormData();
      formData.append('date', report.date);
      formData.append('activities', report.activities);
      formData.append('hours', report.hours.toString());
      
      // Agar photos bo'lsa, ularni qo'shish
      if (report.photos && report.photos.length > 0) {
        report.photos.forEach((photo: any) => {
          formData.append('photos', photo);
        });
      }
      
      const newReport = await apiService.createDailyReport(formData) as any;
      setReports(prev => [...prev, newReport]);
      return newReport;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Hisobot yaratishda xatolik');
      throw err;
    }
  };

  const updateReport = async (id: string, updates: Partial<DailyReport>) => {
    try {
      const updatedReport = await apiService.updateDailyReport(id, updates) as any;
      setReports(prev => 
        prev.map(report => 
          report.id === id ? updatedReport : report
        )
      );
      return updatedReport;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Hisobot yangilashda xatolik');
      throw err;
    }
  };

  const deleteReport = async (id: string) => {
    try {
      await apiService.deleteDailyReport(id);
      setReports(prev => prev.filter(report => report.id !== id));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Hisobot o\'chirishda xatolik');
      throw err;
    }
  };

  return {
    reports,
    loading,
    error,
    addReport,
    updateReport,
    deleteReport,
    refresh: fetchReports
  };
}

// Faculties hook
export function useFaculties() {
  const [faculties, setFaculties] = useState<Faculty[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchFaculties = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await apiService.getFaculties() as any;
      setFaculties(response.results || response);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Xatolik yuz berdi');
      console.error('Faculties fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchFaculties();
  }, []);

  const addFaculty = async (faculty: Omit<Faculty, 'id'>) => {
    try {
      const newFaculty = await apiService.createFaculty(faculty) as any;
      setFaculties(prev => [...prev, newFaculty]);
      return newFaculty;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Fakultet yaratishda xatolik');
      throw err;
    }
  };

  const updateFaculty = async (id: string, updates: Partial<Faculty>) => {
    try {
      const updatedFaculty = await apiService.updateFaculty(id, updates) as any;
      setFaculties(prev => 
        prev.map(faculty => 
          faculty.id === id ? updatedFaculty : faculty
        )
      );
      return updatedFaculty;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Fakultet yangilashda xatolik');
      throw err;
    }
  };

  const deleteFaculty = async (id: string) => {
    try {
      await apiService.deleteFaculty(id);
      setFaculties(prev => prev.filter(faculty => faculty.id !== id));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Fakultet o\'chirishda xatolik');
      throw err;
    }
  };

  return {
    faculties,
    loading,
    error,
    addFaculty,
    updateFaculty,
    deleteFaculty,
    refresh: fetchFaculties
  };
}

// Departments hook
export function useDepartments(facultyId?: string) {
  const [departments, setDepartments] = useState<Department[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchDepartments = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await apiService.getDepartments(facultyId) as any;
      setDepartments(response.results || response);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Xatolik yuz berdi');
      console.error('Departments fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDepartments();
  }, [facultyId]);

  const addDepartment = async (department: Omit<Department, 'id'>) => {
    try {
      const newDepartment = await apiService.createDepartment(department) as any;
      setDepartments(prev => [...prev, newDepartment]);
      return newDepartment;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Kafedra yaratishda xatolik');
      throw err;
    }
  };

  const updateDepartment = async (id: string, updates: Partial<Department>) => {
    try {
      const updatedDepartment = await apiService.updateDepartment(id, updates) as any;
      setDepartments(prev => 
        prev.map(department => 
          department.id === id ? updatedDepartment : department
        )
      );
      return updatedDepartment;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Kafedra yangilashda xatolik');
      throw err;
    }
  };

  const deleteDepartment = async (id: string) => {
    try {
      await apiService.deleteDepartment(id);
      setDepartments(prev => prev.filter(department => department.id !== id));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Kafedra o\'chirishda xatolik');
      throw err;
    }
  };

  return {
    departments,
    loading,
    error,
    addDepartment,
    updateDepartment,
    deleteDepartment,
    refresh: fetchDepartments
  };
}

// Statistics hook
export function useStatistics() {
  const { user } = useAuth();
  const [stats, setStats] = useState<Statistics>({
    totalStudents: 0,
    assignedStudents: 0,
    completedInternships: 0,
    activeCompanies: 0,
    employmentRate: 0,
    averageGrade: 0,
    totalUsers: 0,
    totalSupervisors: 0,
    totalCompanies: 0,
    activeInternships: 0,
    gradedInternships: 0,
    confirmedInternships: 0
  });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

    const fetchStats = async () => {
      try {
      setLoading(true);
      setError(null);
      const response = await apiService.getDashboard() as any;
        setStats({
          totalStudents: response.total_students || 0,
          assignedStudents: response.assigned_students || 0,
          completedInternships: response.completed_internships || 0,
          activeCompanies: response.active_companies || 0,
          employmentRate: response.employment_rate || 0,
          averageGrade: response.average_grade || 0,
          totalUsers: response.total_users || 0,
          totalSupervisors: response.total_supervisors || 0,
          totalCompanies: response.total_companies || 0,
          activeInternships: response.active_internships || 0,
          gradedInternships: response.graded_internships || 0,
          confirmedInternships: response.confirmed_internships || 0
        });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Statistika yuklashda xatolik');
      console.error('Statistics fetch error:', err);
      } finally {
        setLoading(false);
      }
    };

  useEffect(() => {
    if (user) {
      fetchStats();
    }
  }, [user]);

  return { 
    stats,
    loading, 
    error,
    refresh: fetchStats
  };
}

// Import useAuth hook
import { useAuth } from '../contexts/AuthContext';

// Mock data for new hooks
const mockDocuments: Document[] = [
  {
    id: '1',
    student: '1',
    internship: '1',
    type: 'other',
    name: 'Amaliyot to\'g\'risidagi qonunlar',
    file: '/documents/normative-laws.pdf',
    uploaded_at: '2024-01-15',
    status: 'approved'
  },
  {
    id: '2',
    student: '1',
    internship: '1',
    type: 'other',
    name: 'Muassasa buyruqlari jamlanmasi',
    file: '/documents/institution-orders.pdf',
    uploaded_at: '2024-01-20',
    status: 'approved'
  }
];

const mockInternshipPlaces: InternshipPlace[] = [
  {
    id: '1',
    studentId: '1',
    organizationType: 'private_company',
    organizationName: 'UZINFOCOM',
    address: 'Toshkent sh., Amir Temur ko\'ch., 108',
    supervisorName: 'Akmal Karimov',
    supervisorPosition: 'Loyiha menejeri',
    supervisorPhone: '+998712501010',
    supervisorEmail: 'akmal@uzinfocom.uz',
    startDate: '2024-02-01',
    endDate: '2024-04-01',
    workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    description: 'Web dasturlash va ma\'lumotlar bazasi bilan ishlash',
    status: 'approved'
  }
];

const mockGrades: Grade[] = [
  {
    id: '1',
    studentId: '1',
    date: '2024-01-15',
    type: 'daily',
    score: 85,
    maxScore: 100,
    comment: 'Yaxshi ish bajarildi',
    supervisorId: '1'
  }
];

// Mock reports data (currently unused but may be needed for future features)
// const mockReports: DailyReport[] = [
//   {
//     id: '1',
//     studentId: '1',
//     internshipId: '1',
//     date: '2024-01-15',
//     activities: 'Web dasturlash asoslari o\'rganildi, HTML/CSS bilan tanishdim',
//     hours: 8,
//     status: 'approved',
//     feedback: 'Yaxshi ish!',
//     supervisorFeedback: 'Talaba faol ishtirok etdi'
//   },
//   {
//     id: '2',
//     studentId: '1',
//     internshipId: '1',
//     date: '2024-01-16',
//     activities: 'JavaScript asoslari, DOM manipulyatsiyasi',
//     hours: 8,
//     status: 'pending'
//   }
// ];

// New hooks
export function useDocuments() {
  const [documents, setDocuments] = useState<Document[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setDocuments(mockDocuments);
      setLoading(false);
    }, 500);
  }, []);

  const addDocument = (document: Omit<Document, 'id'>) => {
    const newDocument: Document = {
      ...document,
      id: Date.now().toString()
    };
    setDocuments(prev => [...prev, newDocument]);
  };

  const updateDocument = (id: string, updates: Partial<Document>) => {
    setDocuments(prev => 
      prev.map(doc => 
        doc.id === id ? { ...doc, ...updates } : doc
      )
    );
  };

  const deleteDocument = (id: string) => {
    setDocuments(prev => prev.filter(doc => doc.id !== id));
  };

  return { 
    documents, 
    loading, 
    addDocument, 
    updateDocument, 
    deleteDocument 
  };
}

export function useInternshipPlaces() {
  const [places, setPlaces] = useState<InternshipPlace[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setPlaces(mockInternshipPlaces);
      setLoading(false);
    }, 500);
  }, []);

  const addPlace = (place: Omit<InternshipPlace, 'id'>) => {
    const newPlace: InternshipPlace = {
      ...place,
      id: Date.now().toString()
    };
    setPlaces(prev => [...prev, newPlace]);
  };

  const updatePlace = (id: string, updates: Partial<InternshipPlace>) => {
    setPlaces(prev => 
      prev.map(place => 
        place.id === id ? { ...place, ...updates } : place
      )
    );
  };

  return { 
    places, 
    loading, 
    addPlace, 
    updatePlace 
  };
}

export function useGrades() {
  const [grades, setGrades] = useState<Grade[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setGrades(mockGrades);
      setLoading(false);
    }, 500);
  }, []);

  const addGrade = (grade: Omit<Grade, 'id'>) => {
    const newGrade: Grade = {
      ...grade,
      id: Date.now().toString()
    };
    setGrades(prev => [...prev, newGrade]);
  };

  return { 
    grades, 
    loading, 
    addGrade 
  };
}

export function useAdminSettings() {
  const [settings, setSettings] = useState<AdminSettings>({
    id: '1',
    siteName: 'Talabalar Amaliyoti Platformasi',
    siteDescription: 'Universitet talabalarining amaliyot jarayonini boshqarish tizimi',
    contactEmail: 'admin@university.uz',
    contactPhone: '+998712345678',
    address: 'Toshkent sh., Universitet ko\'ch., 1',
    theme: 'light',
    language: 'uz'
  });
  const [loading] = useState(false);

  const updateSettings = (updates: Partial<AdminSettings>) => {
    setSettings(prev => ({ ...prev, ...updates }));
  };

  return { 
    settings, 
    loading, 
    updateSettings 
  };
}

// Internship yaratish funksiyasi
export function useInternshipCreation() {
  const createInternship = async (internshipData: any) => {
    try {
      const response = await apiService.createInternship(internshipData);
      console.log('Internship created:', response);
      return response;
    } catch (error) {
      console.error('Error creating internship:', error);
      throw error;
    }
  };

  return { createInternship };
}

// Amaliyotlar hook
export function useInternships() {
  const [internships, setInternships] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchInternships = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await apiService.getInternships() as any;
      const internshipsData = response.results || response;
      setInternships(internshipsData);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Amaliyotlar yuklashda xatolik');
      console.error('Internships fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInternships();
  }, []);

  const getStudentInternship = (studentId: string | number) => {
    const studentIdNum = typeof studentId === 'string' ? parseInt(studentId) : studentId;
    
    const found = internships.find(internship => {
      const internshipStudentId = typeof internship.student === 'object' 
        ? internship.student?.id 
        : internship.student;
      
      return internshipStudentId == studentIdNum || internshipStudentId == studentId;
    });
    
    return found;
  };

  return { 
    internships, 
    loading, 
    error, 
    getStudentInternship,
    refresh: fetchInternships 
  };
}