export interface User {
  id: string;
  username: string;
  phone?: string;
  role: 'super_admin' | 'admin' | 'student' | 'supervisor';
  name: string;
  avatar?: string;
  student_id?: string; // Student ID qo'shildi
  supervisor_id?: string; // Supervisor ID qo'shildi
}

export interface Student {
  id: string;
  name: string;
  full_name?: string;
  student_id?: string;
  hemisId?: string;
  faculty: string;
  department: string;
  course: number;
  group: string;
  phone: string;
  birthDate?: string;
  passport?: string;
  address?: string;
  parentPhone?: string;
  internshipType: 'belgilanmagan' | 'malaka' | 'pedagogik' | 'ilmiy' | 'ishlab_chiqarish';
  internshipStatus: 'waiting' | 'assigned' | 'start_pending' | 'started' | 'completed' | 'grading' | 'graded' | 'confirmed' | 'cancelled';
  supervisorId?: string;
  companyId?: string;
  supervisorName?: string;
  supervisorPosition?: string;
  companyName?: string;
  companyAddress?: string;
  grade?: number;
  startDate?: string;
  endDate?: string;
  autoGeneratedPassword?: string;
  isPasswordChanged?: boolean;
  login_info?: {
    login: string;
    password: string;
    is_password_changed: boolean;
  };
  // HEMIS qo'shimcha ma'lumotlari
  region?: string;
  district?: string;
  gender?: string;
  jshshir?: string;
  educationLanguage?: string;
  academicYear?: string;
  semester?: string;
  isGraduate?: string;
  specialization?: string;
  educationType?: string;
  educationForm?: string;
}

export interface DailyStatus {
  id: string;
  internship: string;
  date: string;
  status: 'day_start' | 'start_confirmed' | 'start_rejected' | 'report_submitted' | 'report_confirmed' | 'report_rejected' | 'resubmitted' | 'day_completed';
  status_display: string;
  start_time?: string;
  end_time?: string;
  notes?: string;
  rejection_reason?: string;
  created_at: string;
  updated_at: string;
}

export interface Internship {
  id: string;
  student: string;
  student_name: string;
  supervisor: string;
  supervisor_name: string;
  company?: string;
  company_name?: string;
  type: 'malaka' | 'pedagogik' | 'ilmiy' | 'ishlab_chiqarish';
  type_display: string;
  start_date: string;
  end_date: string;
  duration_days?: number;
  status: 'waiting' | 'assigned' | 'start_pending' | 'started' | 'completed' | 'grading' | 'graded' | 'confirmed' | 'cancelled';
  status_display: string;
  grade?: number;
  grade_comment?: string;
  is_graded: boolean;
  graded_by?: string;
  graded_by_name?: string;
  graded_at?: string;
  feedback?: string;
  supervisor_feedback?: string;
  is_active: boolean;
  created_by?: string;
  created_by_name?: string;
  // Progress ma'lumotlari
  progress_percentage?: number;
  completed_days?: number;
  remaining_days?: number;
  attendance_stats?: {
    total_days: number;
    attended_days: number;
    absent_days: number;
    attendance_percentage: number;
    completed_days: number;
    pending_days: number;
  };
  work_days_count?: number;
  daily_statuses?: DailyStatus[];
  created_at: string;
  updated_at: string;
}

export interface Supervisor {
  id: string;
  name: string;
  full_name?: string;
  position: string;
  department: string;
  faculty: string;
  phone: string;
  specialization: string;
  capacity: number;
  assignedStudents: number;
  assigned_students?: number;
  rating: number;
  status: 'active' | 'inactive';
  experience: number;
  autoGeneratedPassword?: string;
  isPasswordChanged?: boolean;
  supervisorId?: string;
  company?: string | number;
  company_name?: string;
  user_id?: number; // User ID for backend API
  user?: {
    id: number;
    username: string;
    first_name: string;
    last_name: string;
    role: string;
  };
}

export interface Company {
  id: string;
  name: string;
  direction: string;
  address: string;
  phone: string;
  capacity: number;
  assignedStudents: number;
  rating: number;
  status: 'active' | 'inactive';
  work_days: string[];
  work_days_display: string[];
  work_hours_start: string;
  work_hours_end: string;
}


export interface DailyReport {
  id: string;
  student: string;
  internship: string;
  date: string;
  activities: string;
  hours: number;
  status: 'pending' | 'approved' | 'rejected';
  photos?: string[];
  rejection_reason?: string;
  supervisor_comment?: string;
  created_at: string;
  updated_at: string;
}

export interface HemisStudent {
  hemisId: string;
  fullName: string;
  studentId: string;
  faculty: string;
  department: string;
  course: number;
  group: string;
  phone?: string;
  birthDate?: string;
  passport?: string;
  address?: string;
  parentPhone?: string;
}

export interface ImportResult {
  success: number;
  failed: number;
  duplicates: number;
  errors: string[];
}

export interface Statistics {
  totalStudents: number;
  assignedStudents: number;
  completedInternships: number;
  activeCompanies: number;
  employmentRate: number;
  averageGrade: number;
  // Super Admin uchun qo'shimcha statistikalar
  totalUsers?: number;
  totalSupervisors?: number;
  totalCompanies?: number;
  activeInternships?: number;
  gradedInternships?: number;
  confirmedInternships?: number;
}

export interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
  read: boolean;
  createdAt: string;
}

export interface Document {
  id: string;
  student: string;
  internship: string;
  type: 'contract' | 'program' | 'report' | 'certificate' | 'other';
  name: string;
  file: string;
  uploaded_at: string;
  status: 'pending' | 'approved' | 'rejected';
  rejection_reason?: string;
}

export interface Faculty {
  id: string;
  name: string;
  description?: string;
  createdAt: string;
}

export interface Department {
  id: string;
  name: string;
  faculty: string;
  faculty_name?: string;
  description?: string;
  createdAt: string;
}

export interface InternshipPlace {
  id: string;
  studentId: string;
  organizationType: 'school' | 'kindergarten' | 'private_company' | 'government' | 'other';
  organizationName: string;
  address: string;
  supervisorName: string;
  supervisorPosition: string;
  supervisorPhone: string;
  supervisorEmail: string;
  startDate: string;
  endDate: string;
  workDays: string[]; // ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
  description?: string;
  status: 'pending' | 'approved' | 'rejected';
}

export interface DailyReportPhoto {
  id: string;
  reportId: string;
  url: string;
  description?: string;
}

export interface Grade {
  id: string;
  studentId: string;
  date: string;
  type: 'daily' | 'final';
  score: number;
  maxScore: number;
  comment?: string;
  supervisorId: string;
}

export interface AdminSettings {
  id: string;
  siteName: string;
  siteDescription: string;
  contactEmail: string;
  contactPhone: string;
  address: string;
  logo?: string;
  theme: 'light' | 'dark';
  language: 'uz' | 'ru' | 'en';
}