"""add organizations areas supervisors

Revision ID: 26d10d3f1e65
Revises: 416634289e9b
Create Date: 2026-04-23 23:04:17.786634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "26d10d3f1e65"
down_revision: Union[str, Sequence[str], None] = "416634289e9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("district", sa.String(length=64), nullable=True),
        sa.Column("geo_lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("geo_lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column(
            "geo_bounds",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="GeoJSON Polygon (optional)",
        ),
        sa.Column(
            "capacity",
            sa.Integer(),
            server_default="30",
            nullable=False,
            comment="Max talabalar soni",
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_areas")),
    )
    op.create_index(op.f("ix_areas_name"), "areas", ["name"], unique=True)
    op.create_index(op.f("ix_areas_region"), "areas", ["region"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False, comment="Masalan '48-maktab'"),
        sa.Column(
            "legal_name",
            sa.String(length=300),
            nullable=True,
            comment="Shartnoma uchun to'liq yuridik nomi",
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "school",
                "mtt",
                "lyceum",
                "college",
                "company",
                "university",
                "other",
                name="organization_kind",
            ),
            nullable=False,
        ),
        sa.Column("director_full_name", sa.String(length=200), nullable=False),
        sa.Column("director_position", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("district", sa.String(length=64), nullable=True),
        sa.Column(
            "address_line", sa.String(length=300), nullable=False, comment="Ko'cha, uy, kvartira"
        ),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("fax", sa.String(length=32), nullable=True),
        sa.Column("inn", sa.String(length=16), nullable=True, comment="INN"),
        sa.Column("bank_name", sa.String(length=200), nullable=True),
        sa.Column(
            "bank_account", sa.String(length=32), nullable=True, comment="H/R — hisob raqami"
        ),
        sa.Column(
            "bank_correspondent",
            sa.String(length=32),
            nullable=True,
            comment="Sh/hr — shartnoma hisob raqami",
        ),
        sa.Column("bank_mfo", sa.String(length=16), nullable=True, comment="MFO"),
        sa.Column(
            "capacity",
            sa.Integer(),
            server_default="10",
            nullable=False,
            comment="Max talabalar soni",
        ),
        sa.Column(
            "work_days",
            sa.ARRAY(sa.Integer()),
            server_default="{1,2,3,4,5}",
            nullable=False,
            comment="Hafta kunlari: 1=Du, 7=Ya",
        ),
        sa.Column(
            "work_hours",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"start": "08:00", "end": "15:00"}',
            nullable=False,
        ),
        sa.Column("geo_lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("geo_lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column(
            "geo_radius_m",
            sa.Integer(),
            server_default="100",
            nullable=False,
            comment="Check-in radius metrda",
        ),
        sa.Column(
            "wifi_ssids",
            sa.ARRAY(sa.String(length=64)),
            server_default="{}",
            nullable=False,
            comment="Attendance WiFi whitelist",
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(op.f("ix_organizations_kind"), "organizations", ["kind"], unique=False)
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_index(op.f("ix_organizations_region"), "organizations", ["region"], unique=False)
    op.create_table(
        "supervisors",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "position",
            sa.String(length=100),
            nullable=False,
            comment="Lavozim, masalan 'O'qituvchi'",
        ),
        sa.Column("specialty", sa.String(length=150), nullable=True, comment="Mutaxassislik"),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column(
            "capacity",
            sa.Integer(),
            server_default="5",
            nullable=False,
            comment="Max biriktirilgan talabalar",
        ),
        sa.Column(
            "rating",
            sa.Numeric(precision=3, scale=2),
            server_default="0.00",
            nullable=False,
            comment="O'rtacha reyting (5 ball, Phase 9 da hisoblanadi)",
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_supervisors_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_supervisors_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supervisors")),
    )
    op.create_index(
        op.f("ix_supervisors_organization_id"), "supervisors", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_supervisors_user_id"), "supervisors", ["user_id"], unique=True)
    # (uq_academic_years_active false positive — saqlab qolamiz)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_supervisors_user_id"), table_name="supervisors")
    op.drop_index(op.f("ix_supervisors_organization_id"), table_name="supervisors")
    op.drop_table("supervisors")
    op.drop_index(op.f("ix_organizations_region"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_kind"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_areas_region"), table_name="areas")
    op.drop_index(op.f("ix_areas_name"), table_name="areas")
    op.drop_table("areas")
    # Postgres enum'ni qo'lda tushirish
    sa.Enum(name="organization_kind").drop(op.get_bind(), checkfirst=False)
