"""add contracts table

Revision ID: 2f299fdf8a29
Revises: 6ef02ae85dc9
Create Date: 2026-04-24 00:13:16.657794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f299fdf8a29"
down_revision: Union[str, Sequence[str], None] = "6ef02ae85dc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column(
            "number", sa.String(length=64), nullable=False, comment="Masalan 'CHDPU-4+2-2025-0001'"
        ),
        sa.Column(
            "template_ref",
            sa.Enum(
                "4_plus_2",
                "pedagogical",
                "qualifying",
                "internship_production",
                "partnership",
                name="contract_template",
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("academic_year_id", sa.Uuid(), nullable=False),
        sa.Column("practice_type_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "students", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "generated", "active", "expired", "revoked", name="contract_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("scan_path", sa.String(length=500), nullable=True),
        sa.Column(
            "qr_token", sa.String(length=64), nullable=False, comment="Public verify URL token"
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "signed_at_org",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Skan yuklangan vaqt",
        ),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["academic_year_id"],
            ["academic_years.id"],
            name=op.f("fk_contracts_academic_year_id_academic_years"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_contracts_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_contracts_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["practice_type_id"],
            ["practice_types.id"],
            name=op.f("fk_contracts_practice_type_id_practice_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
    )
    op.create_index(
        op.f("ix_contracts_academic_year_id"), "contracts", ["academic_year_id"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_created_by_id"), "contracts", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_contracts_number"), "contracts", ["number"], unique=True)
    op.create_index(
        op.f("ix_contracts_organization_id"), "contracts", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_practice_type_id"), "contracts", ["practice_type_id"], unique=False
    )
    op.create_index(op.f("ix_contracts_qr_token"), "contracts", ["qr_token"], unique=True)
    op.create_index(op.f("ix_contracts_status"), "contracts", ["status"], unique=False)
    # (uq_academic_years_active false positive — saqlab qolamiz)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_contracts_status"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_qr_token"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_practice_type_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_organization_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_number"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_created_by_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_academic_year_id"), table_name="contracts")
    op.drop_table("contracts")
    sa.Enum(name="contract_status").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="contract_template").drop(op.get_bind(), checkfirst=False)
