"""Add filters to documents

Revision ID: 3a2423493b44
Revises: b3d2f9a7d5e1
Create Date: 2026-08-10 11:51:44.074158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2423493b44'
down_revision: Union[str, Sequence[str], None] = 'b3d2f9a7d5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('course', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('education_form', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('direction_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_documents_course'), 'documents', ['course'], unique=False)
    op.create_index(op.f('ix_documents_direction_id'), 'documents', ['direction_id'], unique=False)
    op.create_index(op.f('ix_documents_education_form'), 'documents', ['education_form'], unique=False)
    op.create_foreign_key(op.f('fk_documents_direction_id_directions'), 'documents', 'directions', ['direction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_direction_id_directions'), 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_education_form'), table_name='documents')
    op.drop_index(op.f('ix_documents_direction_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_course'), table_name='documents')
    op.drop_column('documents', 'direction_id')
    op.drop_column('documents', 'education_form')
    op.drop_column('documents', 'course')
    # ### end Alembic commands ###
