"""expand student profile with hemis fields

Revision ID: 3d0654406508
Revises: adeaf482c481
Create Date: 2026-04-23 21:35:12.874748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d0654406508"
down_revision: Union[str, Sequence[str], None] = "adeaf482c481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # (uq_academic_years_active — false positive, partial index model'ga kiritilmagan; saqlab qolamiz)

    # Avval enum tiplarini yaratamiz (ADD COLUMN'dan oldin mavjud bo'lishi kerak)
    gender_enum = sa.Enum("male", "female", name="gender")
    gender_enum.create(op.get_bind(), checkfirst=True)
    education_form_enum = sa.Enum(
        "daytime", "evening", "correspondence", "distance", name="education_form"
    )
    education_form_enum.create(op.get_bind(), checkfirst=True)
    degree_type_enum = sa.Enum("bachelor", "master", "phd", name="degree_type")
    degree_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("students", sa.Column("gender", gender_enum, nullable=True))
    op.add_column("students", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column(
        "students", sa.Column("passport_number", sa.String(length=16), nullable=True, comment="PII")
    )
    op.add_column(
        "students", sa.Column("current_semester", sa.Integer(), nullable=True, comment="1-8")
    )
    op.add_column(
        "students", sa.Column("is_graduating", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("students", sa.Column("education_language", sa.String(length=32), nullable=True))
    op.add_column("students", sa.Column("education_form", education_form_enum, nullable=True))
    op.add_column("students", sa.Column("degree_type", degree_type_enum, nullable=True))
    op.alter_column(
        "students",
        "hemis_id",
        existing_type=sa.VARCHAR(length=32),
        comment="HEMIS Talaba ID — masalan '354231100457'",
        existing_comment="HEMIS student_id — masalan '240123456'",
        existing_nullable=False,
    )
    op.drop_column("students", "passport_seria")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column(
            "passport_seria",
            sa.VARCHAR(length=16),
            autoincrement=False,
            nullable=True,
            comment="PII",
        ),
    )
    op.alter_column(
        "students",
        "hemis_id",
        existing_type=sa.VARCHAR(length=32),
        comment="HEMIS student_id — masalan '240123456'",
        existing_comment="HEMIS Talaba ID — masalan '354231100457'",
        existing_nullable=False,
    )
    op.drop_column("students", "degree_type")
    op.drop_column("students", "education_form")
    op.drop_column("students", "education_language")
    op.drop_column("students", "is_graduating")
    op.drop_column("students", "current_semester")
    op.drop_column("students", "passport_number")
    op.drop_column("students", "birth_date")
    op.drop_column("students", "gender")
    # Downgrade'da yangi qo'shilgan enumlarni ham tushirish
    sa.Enum(name="gender").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="education_form").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="degree_type").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
