"""initial

Revision ID: 4b269b8aef80
Revises:
Create Date: 2026-04-23 20:31:51.958519

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4b269b8aef80"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
