"""add practice_assignments

Revision ID: 6ef02ae85dc9
Revises: 26d10d3f1e65
Create Date: 2026-04-23 23:29:33.752783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ef02ae85dc9"
down_revision: Union[str, Sequence[str], None] = "26d10d3f1e65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_assignments",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("practice_type_id", sa.Uuid(), nullable=False),
        sa.Column("academic_year_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("area_id", sa.Uuid(), nullable=True),
        sa.Column("supervisor_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "completed", "cancelled", name="assignment_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("final_grade", sa.Integer(), nullable=True),
        sa.Column("credit_earned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("cancelled_reason", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(organization_id IS NOT NULL AND area_id IS NULL) OR (organization_id IS NULL AND area_id IS NOT NULL)",
            name=op.f("ck_practice_assignments_ck_practice_assignments_object_xor"),
        ),
        sa.CheckConstraint(
            "end_date >= start_date",
            name=op.f("ck_practice_assignments_ck_practice_assignments_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["academic_year_id"],
            ["academic_years.id"],
            name=op.f("fk_practice_assignments_academic_year_id_academic_years"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
            name=op.f("fk_practice_assignments_area_id_areas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_practice_assignments_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["practice_type_id"],
            ["practice_types.id"],
            name=op.f("fk_practice_assignments_practice_type_id_practice_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_practice_assignments_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_id"],
            ["supervisors.id"],
            name=op.f("fk_practice_assignments_supervisor_id_supervisors"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_assignments")),
    )
    op.create_index(
        op.f("ix_practice_assignments_academic_year_id"),
        "practice_assignments",
        ["academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_assignments_area_id"), "practice_assignments", ["area_id"], unique=False
    )
    op.create_index(
        op.f("ix_practice_assignments_organization_id"),
        "practice_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_assignments_practice_type_id"),
        "practice_assignments",
        ["practice_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_assignments_status"), "practice_assignments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_practice_assignments_student_id"),
        "practice_assignments",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_assignments_supervisor_id"),
        "practice_assignments",
        ["supervisor_id"],
        unique=False,
    )
    # (uq_academic_years_active false positive — saqlab qolamiz)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_practice_assignments_supervisor_id"), table_name="practice_assignments")
    op.drop_index(op.f("ix_practice_assignments_student_id"), table_name="practice_assignments")
    op.drop_index(op.f("ix_practice_assignments_status"), table_name="practice_assignments")
    op.drop_index(
        op.f("ix_practice_assignments_practice_type_id"), table_name="practice_assignments"
    )
    op.drop_index(
        op.f("ix_practice_assignments_organization_id"), table_name="practice_assignments"
    )
    op.drop_index(op.f("ix_practice_assignments_area_id"), table_name="practice_assignments")
    op.drop_index(
        op.f("ix_practice_assignments_academic_year_id"), table_name="practice_assignments"
    )
    op.drop_table("practice_assignments")
    sa.Enum(name="assignment_status").drop(op.get_bind(), checkfirst=False)
