"""Add variables to templates and apps

Revision ID: 72e4984da737
Revises: c2deccd1b321
Create Date: 2026-08-11 17:35:23.770604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72e4984da737'
down_revision: Union[str, Sequence[str], None] = 'c2deccd1b321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_templates', sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('practice_applications', sa.Column('variable_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('practice_applications', 'organization_name',
               existing_type=sa.VARCHAR(length=500),
               server_default='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_applications', 'organization_name',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.drop_column('practice_applications', 'variable_values')
    op.drop_column('contract_templates', 'variables')
    # ### end Alembic commands ###
