"""add system settings

Revision ID: a273e821ba2b
Revises: 6854011443c1
Create Date: 2026-05-02 11:57:59.399547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a273e821ba2b'
down_revision: Union[str, Sequence[str], None] = '6854011443c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('site_name', sa.String(length=200), server_default='CHDPU Amaliyot Platformasi', nullable=False),
    sa.Column('site_description', sa.Text(), nullable=True),
    sa.Column('max_file_size_mb', sa.Integer(), server_default='10', nullable=False, comment='Yuklash limit (MB)'),
    sa.Column('allowed_file_types', sa.ARRAY(sa.String(length=16)), server_default='{pdf,jpg,jpeg,png,doc,docx}', nullable=False),
    sa.Column('email_notifications_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), server_default='false', nullable=False, comment="True bo'lsa — super admin'dan tashqari hammaga 503 qaytariladi"),
    sa.Column('maintenance_message', sa.Text(), nullable=True, comment="Maintenance paytida ko'rsatish uchun xabar"),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.drop_index(op.f('uq_academic_years_active'), table_name='academic_years', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_academic_years_active'), 'academic_years', ['is_active'], unique=True, postgresql_where='(is_active = true)')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
