"""add academic structure and students

Revision ID: adeaf482c481
Revises: 1b9ceb64478c
Create Date: 2026-04-23 21:21:29.347060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adeaf482c481"
down_revision: Union[str, Sequence[str], None] = "1b9ceb64478c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_years",
        sa.Column("name", sa.String(length=16), nullable=False, comment="Masalan '2025-2026'"),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_academic_years")),
        sa.UniqueConstraint("name", name=op.f("uq_academic_years_name")),
    )
    op.create_table(
        "faculties",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faculties")),
        sa.UniqueConstraint("code", name=op.f("uq_faculties_code")),
        sa.UniqueConstraint("name", name=op.f("uq_faculties_name")),
    )
    op.create_table(
        "directions",
        sa.Column("faculty_id", sa.Uuid(), nullable=False),
        sa.Column(
            "code",
            sa.String(length=8),
            nullable=False,
            comment="HEMIS yo'nalish kodi, masalan 60110100",
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["faculties.id"],
            name=op.f("fk_directions_faculty_id_faculties"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directions")),
    )
    op.create_index(op.f("ix_directions_code"), "directions", ["code"], unique=True)
    op.create_index(op.f("ix_directions_faculty_id"), "directions", ["faculty_id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.Column("academic_year_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False, comment="Masalan '2301-01'"),
        sa.Column("course", sa.Integer(), nullable=False, comment="1..4"),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["academic_year_id"],
            ["academic_years.id"],
            name=op.f("fk_groups_academic_year_id_academic_years"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["direction_id"],
            ["directions.id"],
            name=op.f("fk_groups_direction_id_directions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint(
            "direction_id", "academic_year_id", "name", name="uq_groups_direction_year_name"
        ),
    )
    op.create_index(
        op.f("ix_groups_academic_year_id"), "groups", ["academic_year_id"], unique=False
    )
    op.create_index(op.f("ix_groups_direction_id"), "groups", ["direction_id"], unique=False)
    op.create_table(
        "students",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "hemis_id",
            sa.String(length=32),
            nullable=False,
            comment="HEMIS student_id — masalan '240123456'",
        ),
        sa.Column("jshshir", sa.String(length=14), nullable=True, comment="PII"),
        sa.Column("passport_seria", sa.String(length=16), nullable=True, comment="PII"),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.Column("district", sa.String(length=64), nullable=True),
        sa.Column("enrollment_year", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("studying", "graduated", "expelled", "academic_leave", name="student_status"),
            server_default="studying",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_students_group_id_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_students_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    op.create_index(op.f("ix_students_group_id"), "students", ["group_id"], unique=False)
    op.create_index(op.f("ix_students_hemis_id"), "students", ["hemis_id"], unique=True)
    op.create_index(op.f("ix_students_status"), "students", ["status"], unique=False)
    op.create_index(op.f("ix_students_user_id"), "students", ["user_id"], unique=True)
    # Faqat bitta aktiv AcademicYear — partial unique index
    op.create_index(
        "uq_academic_years_active",
        "academic_years",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_students_user_id"), table_name="students")
    op.drop_index(op.f("ix_students_status"), table_name="students")
    op.drop_index(op.f("ix_students_hemis_id"), table_name="students")
    op.drop_index(op.f("ix_students_group_id"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_groups_direction_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_academic_year_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_directions_faculty_id"), table_name="directions")
    op.drop_index(op.f("ix_directions_code"), table_name="directions")
    op.drop_table("directions")
    op.drop_table("faculties")
    op.drop_index("uq_academic_years_active", table_name="academic_years")
    op.drop_table("academic_years")
    # Postgres enum'i avtomatik tushmaydi
    sa.Enum(name="student_status").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
