"""Add placeholders_data to applications

Revision ID: b3d2f9a7d5e1
Revises: 8d8cb025771e
Create Date: 2026-08-06 12:49:16.889372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3d2f9a7d5e1'
down_revision: Union[str, Sequence[str], None] = '8d8cb025771e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_applications', sa.Column('placeholders_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_applications', 'placeholders_data')
    # ### end Alembic commands ###
