"""Add scan_file and document_hash to practice_application

Revision ID: c3afea00a423
Revises: 3a2423493b44
Create Date: 2026-08-11 12:49:43.867427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3afea00a423'
down_revision: Union[str, Sequence[str], None] = '3a2423493b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_applications', sa.Column('scan_file', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('practice_applications', sa.Column('document_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_applications', 'document_hash')
    op.drop_column('practice_applications', 'scan_file')
    # ### end Alembic commands ###
